name: Continuous integration example (Custom runner)

on: 
  workflow_dispatch:

jobs:

  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn test
